spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**

server:
  port: 8999

eureka:
  instance:
    host: localhost


