spring:
  application:
    name: FileOperations
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 100MB
      max-file-size: 100MB
      max-request-size: 100MB

file:
  upload-dir: /Users/ajaysingh/Study/FileUpload

