spring:
  application:
    name: s3FileOperations

cloud:
  aws:
    credentials:
      access-key: <key>
      secret-key: <secret>
    region:
      static: us-east-2
    stack:
      auto: false
    bucket:
      name: kunde-auftrage

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error